version: '3.9'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
    ports:
      - '3306:3306'
    healthcheck:
      test: mysqladmin ping -h localhost -P 3306 -u root -p$$DB_ROOT_PASSWORD
      interval: 5s
      timeout: 10s
      retries: 3
    volumes:
      - db:/var/lib/mysql
  express_boilerplate:
    build: .
    env_file: .env
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
networks:
  app-network:
    driver: bridge
volumes:
  db: